# Generated by Django 4.1.7 on 2023-03-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_date_lesson_date_level_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('lvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.level')),
            ],
        ),
    ]
