# Generated by Django 4.1.7 on 2023-03-21 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='first_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='level',
            name='first_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='op1',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='op2',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='op3',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='op4',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
