# Generated by Django 4.1.7 on 2023-03-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_first_lesson_level_first_level_question_op1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='first_lesson',
        ),
    ]
