# Generated by Django 4.1.7 on 2023-03-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lesson_first_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='first_lesson',
            field=models.BooleanField(default=False),
        ),
    ]
