# Generated by Django 4.1.7 on 2023-03-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_first_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='img',
            field=models.ImageField(default=1, upload_to='Lesson_covers'),
            preserve_default=False,
        ),
    ]
