# Generated by Django 4.1.7 on 2023-03-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='Level',
            new_name='level',
        ),
    ]
