# Generated by Django 4.1.7 on 2023-03-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_date_alter_lesson_date_alter_level_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
